{
 "title": "RateFort Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Rate Limit Traffic (Requests/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rate_limit_hits_total[1m])) by (path)",
     "legendFormat": "Hits - {{path}}"
    },
    {
     "expr": "sum(rate(rate_limit_throttles_total[1m])) by (path)",
     "legendFormat": "Throttles - {{path}}"
    }
   ]
  },
  {
   "title": "Total Throttles by Algorithm",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_limit_throttles_total) by (algorithm)",
     "legendFormat": "{{algorithm}}"
    }
   ]
  },
  {
   "title": "Total Successful Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(rate_limit_hits_total)" }
   ]
  },
  {
   "title": "Total Throttled Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate_limit_throttles_total)"
    }
   ]
  }
 ]
}